### ISSUE TITLE
抽离目标代码逻辑，形成代码生成框架

### ISSUE THREAD

**Issue by harttle** [baidu/san-ssr#1]
本代码库提供解析和生成目标代码的框架，并支持可插拔的目标代码生成器。对目标代码生成框架的接口可能是一个包含绑定了源码信息的组件树的 Project 对象。里程碑如下：

- [x] 提供 Project 对象，统一 toPHPCompiler 和 toJSCompiler 接口到 CodeGenerator。
- [x] 抽离 PHPCodeGenerator 到 san-ssr-target-php，PHP 代码离开本仓库
- [x] 抽象 JSCodeGenerator 为 san-ssr-target-js 并内置到 san-ssr，设为 CLI/Programmatic 的默认目标
- [x] 兼容 san.ssr 的现有接口。#39
- [x] 迁移原 unit test #28
- [x] 迁移原 /test/perf 目录至此 #40
- [x] 更改版本约束，并给文档说明。见 https://github.com/baidu/san/issues/441#issuecomment-550260372
